/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspplg;

/**
 *
 * @author PC RPL - R1
 */
public class modul5 extends javax.swing.JFrame {

    /**
     * Creates new form modul5
     */
    public modul5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        cbMakanan1 = new javax.swing.JCheckBox();
        cbMakanan2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbMakanan3 = new javax.swing.JCheckBox();
        cbMakanan4 = new javax.swing.JCheckBox();
        cbMinuman1 = new javax.swing.JCheckBox();
        cbMinuman3 = new javax.swing.JCheckBox();
        cbMinuman2 = new javax.swing.JCheckBox();
        cbMinuman4 = new javax.swing.JCheckBox();
        bPesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        jLabel3.setText("Makanan");

        jLabel4.setText("Minuman");

        tAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlamatActionPerformed(evt);
            }
        });

        cbMakanan1.setText("Friend Fries");
        cbMakanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMakanan1ActionPerformed(evt);
            }
        });

        cbMakanan2.setText("Noodle");
        cbMakanan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMakanan2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesanan");

        cbMakanan3.setText("Cireng");

        cbMakanan4.setText("Seblak");

        cbMinuman1.setText("Kopi Latte");
        cbMinuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMinuman1ActionPerformed(evt);
            }
        });

        cbMinuman3.setText("Matcha");
        cbMinuman3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMinuman3ActionPerformed(evt);
            }
        });

        cbMinuman2.setText("Americano");

        cbMinuman4.setText("Jus Manga");

        bPesan.setText("Pesan");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMakanan2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMakanan4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMakanan1)
                                        .addGap(35, 35, 35)
                                        .addComponent(cbMakanan3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbMinuman2)
                                            .addComponent(cbMinuman1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbMinuman3)
                                            .addComponent(cbMinuman4)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(104, 104, 104)
                                    .addComponent(tNama))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(98, 98, 98)
                                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPesan)
                            .addComponent(jLabel5))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMakanan1)
                    .addComponent(cbMakanan3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMakanan2)
                    .addComponent(cbMakanan4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMinuman1)
                    .addComponent(cbMinuman3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMinuman2)
                    .addComponent(cbMinuman4))
                .addGap(35, 35, 35)
                .addComponent(bPesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMakanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMakanan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMakanan1ActionPerformed

    private void cbMakanan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMakanan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMakanan2ActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
    String Nama = tNama.getText();
    String Alamat = tAlamat.getText();
    
    // Membuat string untuk daftar pesanan
    String pesanan = "Nama: " + Nama + "\nAlamat: " + Alamat + "\n\nPesanan:\n";
    
    // Mengecek pilihan makanan
    if (cbMakanan1.isSelected()) {
        pesanan += "- " + cbMakanan1.getText() + "\n";
    }
    if (cbMakanan2.isSelected()) {
        pesanan += "- " + cbMakanan2.getText() + "\n";
    }
    if (cbMakanan3.isSelected()) {  // Perbaikan di sini
        pesanan += "- " + cbMakanan3.getText() + "\n";
    }
    if (cbMakanan4.isSelected()) {
        pesanan += "- " + cbMakanan4.getText() + "\n";
    }
    
    // Mengecek pilihan minuman
    if (cbMinuman1.isSelected()) {
        pesanan += "- " + cbMinuman1.getText() + "\n";
    }
    if (cbMinuman2.isSelected()) {
        pesanan += "- " + cbMinuman2.getText() + "\n";
    }
    if (cbMinuman3.isSelected()) {
        pesanan += "- " + cbMinuman3.getText() + "\n";
    }
    if (cbMinuman4.isSelected()) {
        pesanan += "- " + cbMinuman4.getText() + "\n";
    }
    
    // Menampilkan pesanan di TextArea
    hasil.setText(pesanan);
    }//GEN-LAST:event_bPesanActionPerformed

    private void cbMinuman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMinuman1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMinuman1ActionPerformed

    private void cbMinuman3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMinuman3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMinuman3ActionPerformed

    private void tAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPesan;
    private javax.swing.JCheckBox cbMakanan1;
    private javax.swing.JCheckBox cbMakanan2;
    private javax.swing.JCheckBox cbMakanan3;
    private javax.swing.JCheckBox cbMakanan4;
    private javax.swing.JCheckBox cbMinuman1;
    private javax.swing.JCheckBox cbMinuman2;
    private javax.swing.JCheckBox cbMinuman3;
    private javax.swing.JCheckBox cbMinuman4;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
